name: GitHub Pages Deploy

on:
  push:
    branches:
      - develop  # Change this to the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change this to the Node.js version you require

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Change this to your build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Change this to your build output directory
